# Generated by Django 4.1.3 on 2022-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_client', models.CharField(max_length=50)),
                ('visit_date', models.CharField(max_length=50)),
                ('visit_hour', models.CharField(max_length=50)),
                ('visit_reason', models.CharField(max_length=300)),
                ('technician_name', models.CharField(max_length=50)),
                ('updateOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
